## 3. Transformation et stockage final des données


**Objectif**

Récupérer les tables temporaires, les transformer pour avoir des données plus compréhensibles et restocker les tables définitives dans la base.

In [3]:
import os
import pandas as pd
# import geopandas as gpd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

# 1. Chargement du fichier .env pour récupérer tes identifiants secrets
load_dotenv()

db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_name = "retail_db"

# 2. DETECTION DE L'ENVIRONNEMENT (Le correctif pour ton erreur)
# Si on est dans Docker, un dossier '/opt/airflow' existe. Sinon, on est sur ton Windows.
if os.path.exists("/opt/airflow"):
    db_host = "postgres-gis"  # Connexion interne Docker
    print("[Info] Exécution détectée dans le conteneur DOCKER.")
else:
    db_host = "localhost"     # Connexion depuis VS Code Windows
    print("[Info] Exécution détectée en LOCAL (Windows VS Code).")

# 3. Construction de la chaîne de connexion
DATABASE_URL = f"postgresql://{db_user}:{db_password}@{db_host}:5432/{db_name}"
engine = create_engine(DATABASE_URL)

# 4. Test de la connexion
with engine.connect() as conn:
    conn.execute(text("CREATE EXTENSION IF NOT EXISTS postgis;"))
    # conn.commit()

print("[OK] Connexion sécurisée établie avec succès ! extension PostGIS active.")

python-dotenv could not parse statement starting at line 20
python-dotenv could not parse statement starting at line 21

[Info] Exécution détectée en LOCAL (Windows VS Code).
[OK] Connexion sécurisée établie avec succès ! extension PostGIS active.

##### Table stg_population_attractivité

In [36]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_attractivité;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")

# 2. Transformation - Étape A : Pivot des lignes en colonnes
# On veut que chaque code de 'FILOSOFI_MEASURE' devienne une vraie colonne distincte
df_transforme = df_brut.pivot(
    index=['GEO', 'TIME_PERIOD'], 
    columns='FILOSOFI_MEASURE', 
    values='OBS_VALUE_NIVEAU'
).reset_index()
df_transforme

[Info] Données brutes extraites de PostgreSQL : 10000 lignes.

FILOSOFI_MEASURE,GEO,TIME_PERIOD,D1_SL,D2_SL,D3_SL,D4_SL,D6_SL,D7_SL,D8_SL,D9_SL,...,S_EI_DI,S_EI_DI_N_SAL,S_EI_DI_SAL,S_EI_DI_UNE,S_INC_ASS_DI,S_RET_PEN_DI,S_SOC_BEN_DI,S_SOC_BEN_DI_FAM_BEN,S_SOC_BEN_DI_HOU_BEN,S_SOC_BEN_DI_MIN_SOC
0,2026-COM-75056,2023,5.95697,5.95697,5.95697,5.95697,5.95697,5.95697,5.95697,5.95697,...,5.95697,5.95697,5.95697,33650.0,5.95697,33650.0,33650.0,33650.0,5.95697,5.95697
1,2026-COM-77001,2023,NaN,31040.00000,33650.00000,NaN,34160.00000,32740.00000,28420.00000,NaN,...,12.00000,27830.00000,34160.00000,27020.0,32250.00000,33120.0,27830.0,32260.0,34160.00000,13.00000
2,2026-COM-77002,2023,6.00000,30140.00000,26460.00000,27540.00000,9.00000,32740.00000,29900.00000,13.00000,...,27540.00000,26460.00000,27570.00000,NaN,NaN,NaN,13.0,NaN,29130.00000,25960.00000
3,2026-COM-77003,2023,9.00000,27700.00000,33120.00000,25450.00000,26460.00000,NaN,23730.00000,37060.00000,...,29730.00000,27830.00000,29130.00000,31170.0,NaN,23730.0,27000.0,NaN,13.00000,26.00000
4,2026-COM-77004,2023,13.00000,32740.00000,31510.00000,25960.00000,NaN,NaN,12.00000,NaN,...,7.00000,NaN,27100.00000,27830.0,37060.00000,25450.0,26.0,27000.0,30140.00000,25960.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2026-COM-77480,2023,27830.00000,NaN,NaN,NaN,NaN,NaN,28180.00000,NaN,...,NaN,NaN,NaN,27830.0,27080.00000,NaN,24270.0,NaN,NaN,NaN
460,2026-COM-77481,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24270.00000,NaN,NaN,10.0,NaN,27080.0,17.00000,24660.00000
461,2026-COM-77482,2023,NaN,27830.00000,NaN,33690.00000,25930.00000,NaN,NaN,NaN,...,NaN,NaN,28830.00000,NaN,NaN,NaN,NaN,29670.0,NaN,NaN
462,2026-COM-77483,2023,NaN,NaN,24270.00000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24660.00000,NaN,24660.00000,28830.0,NaN,29670.0,25930.00000,NaN
463,2026-COM-77484,2023,NaN,NaN,NaN,33690.00000,NaN,NaN,NaN,NaN,...,NaN,29670.00000,NaN,29670.0,NaN,NaN,24270.0,NaN,NaN,24660.00000

In [37]:
# 3. Transformation - Étape B : Renommer les colonnes avec des noms explicites
# On transforme les codes barbares de l'INSEE en français compréhensible
dictionnaire_noms = {
    # Identifiants
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",

    # Indicateurs de pauvreté et niveau de vie
    "PR_MD60": "taux_pauvrete_60",
    "MED_SL": "niveau_vie_median",
    "GI_SL": "indice_gini",
    "S80S20_SL": "rapport_interquintile_s80_s20",
    "IQR_SL": "ecart_interquartile",
    "IR_D9_D1_SL": "rapport_decile_d9_d1",

    # Déciles de niveau de vie
    "D1_SL": "premier_decile_niveau_vie",
    "D2_SL": "deuxieme_decile_niveau_vie",
    "D3_SL": "troisieme_decile_niveau_vie",
    "D4_SL": "quatrieme_decile_niveau_vie",
    "D5_SL": "cinquieme_decile_niveau_vie",
    "D6_SL": "sixieme_decile_niveau_vie",
    "D7_SL": "septieme_decile_niveau_vie",
    "D8_SL": "huitieme_decile_niveau_vie",
    "D9_SL": "neuvieme_decile_niveau_vie",

    # Quartiles
    "Q1_SL": "premier_quartile_niveau_vie",
    "Q3_SL": "troisieme_quartile_niveau_vie",

    # Revenus d'activité
    "S_EI_DI": "part_revenus_activite_independants",
    "S_EI_DI_SAL": "part_revenus_activite_salaries",
    "S_EI_DI_N_SAL": "part_revenus_activite_non_salaries",
    "S_EI_DI_UNE": "part_revenus_activite_chomage",

    # Retraites
    "S_RET_PEN_DI": "part_retraites_pensions",

    # Prestations sociales
    "S_SOC_BEN_DI": "part_prestations_sociales",
    "S_SOC_BEN_DI_FAM_BEN": "part_prestations_familiales",
    "S_SOC_BEN_DI_HOU_BEN": "part_aides_logement",
    "S_SOC_BEN_DI_MIN_SOC": "part_minima_sociaux",

    # Fiscalité
    "S_DIR_TAX_DI": "part_impots_directs",

    # Autres revenus
    "S_INC_ASS_DI": "part_revenus_patrimoine_assurance"
}

df_pop_attractivite = df_transforme.rename(columns=dictionnaire_noms)

# Chargement de la table finale dans la base de données
df_pop_attractivite.to_sql("fin_attractivite_socioeconomique", con=engine, if_exists="replace", index=False)

df_pop_attractivite

FILOSOFI_MEASURE,code_zone_insee,annee_recensement,premier_decile_niveau_vie,deuxieme_decile_niveau_vie,troisieme_decile_niveau_vie,quatrieme_decile_niveau_vie,sixieme_decile_niveau_vie,septieme_decile_niveau_vie,huitieme_decile_niveau_vie,neuvieme_decile_niveau_vie,...,part_revenus_activite_independants,part_revenus_activite_non_salaries,part_revenus_activite_salaries,part_revenus_activite_chomage,part_revenus_patrimoine_assurance,part_retraites_pensions,part_prestations_sociales,part_prestations_familiales,part_aides_logement,part_minima_sociaux
0,2026-COM-75056,2023,5.95697,5.95697,5.95697,5.95697,5.95697,5.95697,5.95697,5.95697,...,5.95697,5.95697,5.95697,33650.0,5.95697,33650.0,33650.0,33650.0,5.95697,5.95697
1,2026-COM-77001,2023,NaN,31040.00000,33650.00000,NaN,34160.00000,32740.00000,28420.00000,NaN,...,12.00000,27830.00000,34160.00000,27020.0,32250.00000,33120.0,27830.0,32260.0,34160.00000,13.00000
2,2026-COM-77002,2023,6.00000,30140.00000,26460.00000,27540.00000,9.00000,32740.00000,29900.00000,13.00000,...,27540.00000,26460.00000,27570.00000,NaN,NaN,NaN,13.0,NaN,29130.00000,25960.00000
3,2026-COM-77003,2023,9.00000,27700.00000,33120.00000,25450.00000,26460.00000,NaN,23730.00000,37060.00000,...,29730.00000,27830.00000,29130.00000,31170.0,NaN,23730.0,27000.0,NaN,13.00000,26.00000
4,2026-COM-77004,2023,13.00000,32740.00000,31510.00000,25960.00000,NaN,NaN,12.00000,NaN,...,7.00000,NaN,27100.00000,27830.0,37060.00000,25450.0,26.0,27000.0,30140.00000,25960.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,2026-COM-77480,2023,27830.00000,NaN,NaN,NaN,NaN,NaN,28180.00000,NaN,...,NaN,NaN,NaN,27830.0,27080.00000,NaN,24270.0,NaN,NaN,NaN
460,2026-COM-77481,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24270.00000,NaN,NaN,10.0,NaN,27080.0,17.00000,24660.00000
461,2026-COM-77482,2023,NaN,27830.00000,NaN,33690.00000,25930.00000,NaN,NaN,NaN,...,NaN,NaN,28830.00000,NaN,NaN,NaN,NaN,29670.0,NaN,NaN
462,2026-COM-77483,2023,NaN,NaN,24270.00000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,24660.00000,NaN,24660.00000,28830.0,NaN,29670.0,25930.00000,NaN
463,2026-COM-77484,2023,NaN,NaN,NaN,33690.00000,NaN,NaN,NaN,NaN,...,NaN,29670.00000,NaN,29670.0,NaN,NaN,24270.0,NaN,NaN,24660.00000

##### Table stg_population_emploi

In [4]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_emploi;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 2532 lignes.

                 GEO  TIME_PERIOD FLORES_MEASURE ACTIVITY  OBS_VALUE_NIVEAU
0     2026-COM-75056         2024       EMPL3112       _T         2010517.0
1     2026-COM-77001         2024       EMPL3112       _T             158.0
2     2026-COM-77002         2024       EMPL3112       _T             220.0
3     2026-COM-77003         2024       EMPL3112       _T              42.0
4     2026-COM-77004         2024       EMPL3112       _T              19.0
...              ...          ...            ...      ...               ...
2527  2026-COM-95676         2024       UNIT_LOC       _T              13.0
2528  2026-COM-95678         2024       UNIT_LOC       _T              26.0
2529  2026-COM-95680         2024       UNIT_LOC       _T             638.0
2530  2026-COM-95682         2024       UNIT_LOC       _T               9.0
2531  2026-COM-95690         2024       UNIT_LOC       _T              11.0

[2532 rows x 5 columns]

In [8]:
print(df_brut["FLORES_MEASURE"].unique().tolist())
print(df_brut["ACTIVITY"].unique().tolist())

['EMPL3112', 'UNIT_LOC']
['_T']

In [11]:
# 2. Transformation - Étape A : Pivot des lignes en colonnes
# On veut que chaque code de 'FLORES_MEASURE' devienne une vraie colonne distincte
df_transforme = df_brut.pivot(
    index=['GEO', 'TIME_PERIOD'], 
    columns='FLORES_MEASURE', 
    values='OBS_VALUE_NIVEAU'
).reset_index()
df_transforme

FLORES_MEASURE             GEO  TIME_PERIOD   EMPL3112  UNIT_LOC
0               2026-COM-75056         2024  2010517.0  188002.0
1               2026-COM-77001         2024      158.0      35.0
2               2026-COM-77002         2024      220.0      39.0
3               2026-COM-77003         2024       42.0      12.0
4               2026-COM-77004         2024       19.0      13.0
...                        ...          ...        ...       ...
1261            2026-COM-95676         2024       80.0      13.0
1262            2026-COM-95678         2024       73.0      26.0
1263            2026-COM-95680         2024     5260.0     638.0
1264            2026-COM-95682         2024       24.0       9.0
1265            2026-COM-95690         2024       29.0      11.0

[1266 rows x 4 columns]

In [12]:
# 3. Transformation - Étape B : Renommer les colonnes avec des noms explicites
# On transforme les codes barbares de l'INSEE en français compréhensible
dictionnaire_noms = {
    # Identifiants
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",
    # "ACTIVITY": "code_secteur_activite",
    "UNIT_LOC": "nombre_etablissements",
    "EMPL3112": "nombre_salaries"
}

df_pop_emploi = df_transforme.rename(columns=dictionnaire_noms)

# Chargement de la table finale dans la base de données
df_pop_emploi.to_sql("fin_population_emploi", con=engine, if_exists="replace", index=False)

df_pop_emploi

FLORES_MEASURE,code_zone_insee,annee_recensement,nombre_salaries,nombre_etablissements
0,2026-COM-75056,2024,2010517.0,188002.0
1,2026-COM-77001,2024,158.0,35.0
2,2026-COM-77002,2024,220.0,39.0
3,2026-COM-77003,2024,42.0,12.0
4,2026-COM-77004,2024,19.0,13.0
...,...,...,...,...
1261,2026-COM-95676,2024,80.0,13.0
1262,2026-COM-95678,2024,73.0,26.0
1263,2026-COM-95680,2024,5260.0,638.0
1264,2026-COM-95682,2024,24.0,9.0
1265,2026-COM-95690,2024,29.0,11.0

##### Table stg_population_infrastructure

In [18]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_infrastructure;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 22630 lignes.

,GEO,BPE_MEASURE,FACILITY_SDOM,FACILITY_TYPE,TIME_PERIOD,UNIT_MEASURE,FACILITY_DOM,OBS_STATUS,UNIT_MULT,OBS_VALUE_NIVEAU
0,2026-COM-75056,FACILITIES,E1,E107,2025,NR,E,A,0,7.0
1,2026-COM-77111,FACILITIES,E1,E107,2025,NR,E,A,0,1.0
2,2026-COM-91377,FACILITIES,E1,E107,2025,NR,E,A,0,1.0
3,2026-COM-93073,FACILITIES,E1,E107,2025,NR,E,A,0,1.0
4,2026-COM-75056,FACILITIES,E1,E108,2025,NR,E,A,0,27.0
...,...,...,...,...,...,...,...,...,...,...
22625,2026-COM-95424,FACILITIES,D3,D307,2025,NR,D,A,0,5.0
22626,2026-COM-95369,FACILITIES,D3,D307,2025,NR,D,A,0,1.0
22627,2026-COM-95582,FACILITIES,D3,D307,2025,NR,D,A,0,9.0
22628,2026-COM-95539,FACILITIES,D3,D307,2025,NR,D,A,0,4.0
22629,2026-COM-95604,FACILITIES,D3,D307,2025,NR,D,A,0,1.0

In [20]:
doublons = (
    df_brut
    .groupby(['GEO', 'TIME_PERIOD', 'FACILITY_TYPE'])
    .size()
    .reset_index(name='nb')
)

doublons = doublons[doublons['nb'] > 1]

doublons

                  GEO  TIME_PERIOD FACILITY_TYPE  nb
0      2026-COM-75056         2025          A203   2
1      2026-COM-75056         2025          A206   2
2      2026-COM-75056         2025          A504   2
3      2026-COM-75056         2025          B104   2
4      2026-COM-75056         2025          B105   2
...               ...          ...           ...  ..
11310  2026-COM-95680         2025          F120   2
11311  2026-COM-95680         2025          F121   2
11312  2026-COM-95682         2025          F120   2
11313  2026-COM-95690         2025          C109   2
11314  2026-COM-95690         2025          F116   2

[11315 rows x 4 columns]

In [25]:
df_brut = df_brut.drop_duplicates()

In [26]:
print(df_brut["BPE_MEASURE"].unique().tolist())
print(df_brut["FACILITY_SDOM"].unique().tolist())
print(df_brut["FACILITY_TYPE"].unique().tolist())
print(df_brut["FACILITY_DOM"].unique().tolist())

['FACILITIES']
['E1', 'F1', 'A2', 'A5', 'B1', 'B2', 'B3', 'C1', 'C2', 'C3', 'D1', 'D3']
['E107', 'E108', 'E109', 'F119', 'F120', 'F121', 'F116', 'A203', 'A206', 'A504', 'B104', 'B105', 'B201', 'B202', 'B207', 'B302', 'B304', 'B306', 'B310', 'B321', 'B324', 'B325', 'C107', 'C108', 'C109', 'C201', 'C301', 'D106', 'D307']
['E', 'F', 'A', 'B', 'C', 'D']

In [27]:
df_bpe = df_brut.pivot(
    index=['GEO', 'TIME_PERIOD'], 
    columns='FACILITY_TYPE', 
    values='OBS_VALUE_NIVEAU'
).reset_index()
df_bpe

FACILITY_TYPE,GEO,TIME_PERIOD,A203,A206,A504,B104,B105,B201,B202,B207,...,C301,D106,D307,E107,E108,E109,F116,F119,F120,F121
0,2026-COM-75056,2025,1265.0,128.0,20911.0,44.0,715.0,368.0,2106.0,2307.0,...,173.0,16.0,864.0,7.0,27.0,NaN,88.0,6.0,244.0,267.0
1,2026-COM-77001,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,2026-COM-77002,2025,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,2026-COM-77003,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-COM-77004,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185,2026-COM-95676,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1186,2026-COM-95678,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
1187,2026-COM-95680,2025,2.0,1.0,73.0,NaN,5.0,2.0,21.0,16.0,...,2.0,NaN,9.0,NaN,NaN,NaN,12.0,NaN,3.0,7.0
1188,2026-COM-95682,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
1189,2026-COM-95690,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

In [28]:
dictionnaire_bpe = {

    # Identifiants
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",
    
    # =========================
    # A - SERVICES AUX PARTICULIERS
    # =========================
    "A203": "banque",
    "A206": "bureau_de_poste",
    "A504": "restauration_rapide",

    # =========================
    # B - COMMERCES
    # =========================
    "B104": "hypermarche_grand_magasin",
    "B105": "supermarche",
    "B201": "superette",
    "B202": "epicerie",
    "B207": "boulangerie_patisserie",
    "B302": "magasin_vetements",
    "B304": "magasin_chaussures",
    "B306": "magasin_meubles",
    "B310": "parfumerie_cosmetique",
    "B321": "electromenager_audio_video_informatique",
    "B324": "librairie",
    "B325": "papeterie_presse",

    # =========================
    # C - ENSEIGNEMENT
    # =========================
    "C107": "ecole_maternelle",
    "C108": "ecole_primaire",
    "C109": "ecole_elementaire",
    "C201": "college",
    "C301": "lycee",

    # =========================
    # D - SANTE
    # =========================
    "D106": "urgences",
    "D307": "pharmacie",

    # =========================
    # E - TRANSPORTS
    # =========================
    "E107": "gare_nationale",
    "E108": "gare_regionale",
    "E109": "transport_ferroviaire_local_rer_metro_transilien",

    # =========================
    # F - SPORTS / LOISIRS
    # =========================
    "F119": "bowling",
    "F120": "salle_remise_en_forme",
    "F121": "gymnase_multisports",
    "F116": "salle_non_specialisee_sport"
}

# Assignation à ta nouvelle variable
df_pop_infrastructure = df_bpe


df_pop_infrastructure = df_pop_infrastructure.rename(columns=dictionnaire_bpe)

# Chargement de la table finale dans la base de données
df_pop_infrastructure.to_sql("fin_infrastructures_de_proximite", con=engine, if_exists="replace", index=False)

df_pop_infrastructure

FACILITY_TYPE,code_zone_insee,annee_recensement,banque,bureau_de_poste,restauration_rapide,hypermarche_grand_magasin,supermarche,superette,epicerie,boulangerie_patisserie,...,lycee,urgences,pharmacie,gare_nationale,gare_regionale,transport_ferroviaire_local_rer_metro_transilien,salle_non_specialisee_sport,bowling,salle_remise_en_forme,gymnase_multisports
0,2026-COM-75056,2025,1265.0,128.0,20911.0,44.0,715.0,368.0,2106.0,2307.0,...,173.0,16.0,864.0,7.0,27.0,NaN,88.0,6.0,244.0,267.0
1,2026-COM-77001,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,2026-COM-77002,2025,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
3,2026-COM-77003,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-COM-77004,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185,2026-COM-95676,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1186,2026-COM-95678,2025,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
1187,2026-COM-95680,2025,2.0,1.0,73.0,NaN,5.0,2.0,21.0,16.0,...,2.0,NaN,9.0,NaN,NaN,NaN,12.0,NaN,3.0,7.0
1188,2026-COM-95682,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
1189,2026-COM-95690,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN

##### Table stg_population_logement

In [34]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_logement;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 27852 lignes.

                  GEO  TIME_PERIOD    NOR      OCS  L_STAY  OBS_VALUE_NIVEAU
0      2026-COM-75056         2023     _T  DW_MAIN  Y10T19      198821.63183
1      2026-COM-75056         2023     _T  DW_MAIN  Y20T29      138351.28940
2      2026-COM-75056         2023     _T  DW_MAIN    Y2T4      271313.38030
3      2026-COM-75056         2023     _T  DW_MAIN    Y5T9      196659.40251
4      2026-COM-75056         2023     _T  DW_MAIN  Y_GE30      148080.43683
...               ...          ...    ...      ...     ...               ...
27847  2026-COM-95690         2017     R1  DW_MAIN      _T           1.01383
27848  2026-COM-95690         2017     R2  DW_MAIN      _T           6.07222
27849  2026-COM-95690         2017     R3  DW_MAIN      _T          17.11712
27850  2026-COM-95690         2017     R4  DW_MAIN      _T          25.97596
27851  2026-COM-95690         2017  R_GE5  DW_MAIN      _T          95.82087

[27852 rows x 6 columns]

In [39]:
df_logement = df_brut.copy()

df_logement["INDICATEUR_LOGEMENT"] = None

# Ancienneté d'emménagement
df_logement.loc[
    df_logement["NOR"] == "_T",
    "INDICATEUR_LOGEMENT"
] = "anciennete_" + df_logement["L_STAY"]

# Nombre de pièces
df_logement.loc[
    df_logement["L_STAY"] == "_T",
    "INDICATEUR_LOGEMENT"
] = "pieces_" + df_logement["NOR"]
df_logement

,GEO,TIME_PERIOD,NOR,OCS,L_STAY,OBS_VALUE_NIVEAU,INDICATEUR_LOGEMENT
0,2026-COM-75056,2023,_T,DW_MAIN,Y10T19,198821.63183,anciennete_Y10T19
1,2026-COM-75056,2023,_T,DW_MAIN,Y20T29,138351.28940,anciennete_Y20T29
2,2026-COM-75056,2023,_T,DW_MAIN,Y2T4,271313.38030,anciennete_Y2T4
3,2026-COM-75056,2023,_T,DW_MAIN,Y5T9,196659.40251,anciennete_Y5T9
4,2026-COM-75056,2023,_T,DW_MAIN,Y_GE30,148080.43683,anciennete_Y_GE30
...,...,...,...,...,...,...,...
27847,2026-COM-95690,2017,R1,DW_MAIN,_T,1.01383,pieces_R1
27848,2026-COM-95690,2017,R2,DW_MAIN,_T,6.07222,pieces_R2
27849,2026-COM-95690,2017,R3,DW_MAIN,_T,17.11712,pieces_R3
27850,2026-COM-95690,2017,R4,DW_MAIN,_T,25.97596,pieces_R4
27851,2026-COM-95690,2017,R_GE5,DW_MAIN,_T,95.82087,pieces_R_GE5

In [41]:
dico_indicateurs = {
    "anciennete_Y_LT2": "logements_moins_2_ans",
    "anciennete_Y2T4": "logements_2_4_ans",
    "anciennete_Y5T9": "logements_5_9_ans",
    "anciennete_Y10T19": "logements_10_19_ans",
    "anciennete_Y20T29": "logements_20_29_ans",
    "anciennete_Y_GE30": "logements_30_ans_ou_plus",

    "pieces_R1": "logements_1_piece",
    "pieces_R2": "logements_2_pieces",
    "pieces_R3": "logements_3_pieces",
    "pieces_R4": "logements_4_pieces",
    "pieces_R_GE5": "logements_5_pieces_ou_plus"
}

df_logement["INDICATEUR_LOGEMENT"] = (
    df_logement["INDICATEUR_LOGEMENT"]
    .map(dico_indicateurs)
)

In [42]:
doublons = (
    df_logement
    .groupby(["GEO", "TIME_PERIOD", "INDICATEUR_LOGEMENT"])
    .size()
    .reset_index(name="nb")
)

print(doublons[doublons["nb"] > 1])

Empty DataFrame
Columns: [GEO, TIME_PERIOD, INDICATEUR_LOGEMENT, nb]
Index: []

In [43]:
df_logement = df_logement.rename(columns={'GEO': 'code_zone_insee', 'TIME_PERIOD': 'annee_recensement'})

In [44]:
df_population_logement = (
    df_logement
    .pivot(
        index=["code_zone_insee", "annee_recensement"],
        columns="INDICATEUR_LOGEMENT",
        values="OBS_VALUE_NIVEAU"
    )
    .reset_index()
)

df_population_logement.columns.name = None
df_population_logement

,code_zone_insee,annee_recensement,logements_10_19_ans,logements_1_piece,logements_20_29_ans,logements_2_4_ans,logements_2_pieces,logements_30_ans_ou_plus,logements_3_pieces,logements_4_pieces,logements_5_9_ans,logements_5_pieces_ou_plus,logements_moins_2_ans
0,2026-COM-75056,2017,234759.08383,263138.04296,117450.31250,267134.39926,360437.41744,154795.67821,267711.74341,146924.55996,191711.69375,103411.34700,175771.94322
1,2026-COM-75056,2023,198821.63183,261901.41711,138351.28940,271313.38030,348906.93966,148080.43683,265404.16931,144776.45608,196659.40251,103533.37426,171296.21555
2,2026-COM-77001,2017,148.58681,8.54964,67.95784,55.83149,11.66424,84.56348,37.07821,109.52308,70.85014,295.18484,34.21023
3,2026-COM-77001,2023,140.32916,1.06465,82.42404,66.53873,5.32427,105.40909,36.25013,109.31837,69.35022,348.66740,36.57357
4,2026-COM-77002,2017,78.56030,8.94991,42.76067,53.69945,19.88868,58.67162,38.78293,86.51577,54.69388,167.06494,32.81633
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527,2026-COM-95680,2023,2584.46340,463.56788,1288.21127,1823.39796,1897.76573,1289.88603,3557.62648,2655.97977,2326.92053,1618.62779,880.68846
2528,2026-COM-95682,2017,8.80952,0.00000,17.61905,12.72487,5.87302,10.76720,8.80952,17.61905,9.78836,38.17460,10.76720
2529,2026-COM-95682,2023,13.04545,0.00000,12.11364,12.11364,2.79545,14.90909,11.18182,16.77273,19.56818,43.79545,2.79545
2530,2026-COM-95690,2017,42.02492,1.01383,21.98417,14.98270,6.07222,27.21239,17.11712,25.97596,27.83300,95.82087,11.96283
2531,2026-COM-95690,2023,32.97463,0.00000,29.02179,18.81336,5.05905,32.25007,14.00418,31.02492,26.81042,101.76983,11.98770

In [45]:
# Chargement de la table finale dans la base de données
df_population_logement.to_sql("fin_caracteristiques_logement", con=engine, if_exists="replace", index=False)

532

##### Table stg_population_pouvoir_achat

In [46]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_pouvoir_achat;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 1795 lignes.

                 GEO  TIME_PERIOD FILOSOFI_MEASURE  OBS_VALUE_NIVEAU
0     2026-COM-75056         2023           MED_SL           33650.0
1     2026-COM-75056         2023          PR_MD60              16.8
2     2026-COM-77001         2023           MED_SL           34840.0
3     2026-COM-77002         2023           MED_SL           29130.0
4     2026-COM-77003         2023           MED_SL           30310.0
...              ...          ...              ...               ...
1790  2026-COM-95678         2023           MED_SL           34300.0
1791  2026-COM-95680         2023           MED_SL           17750.0
1792  2026-COM-95680         2023          PR_MD60              39.4
1793  2026-COM-95682         2023           MED_SL           28800.0
1794  2026-COM-95690         2023           MED_SL           35370.0

[1795 rows x 4 columns]

In [47]:
df_brut1 = df_brut[['GEO', 'TIME_PERIOD', 'FILOSOFI_MEASURE','OBS_VALUE_NIVEAU']]

In [48]:
dico_colonnes = {
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",
    "FILOSOFI_MEASURE": "indicateur",
    "OBS_VALUE_NIVEAU": "valeur"
    # "UNIT_MEASURE": "unite_measure"
}

df_pouvoir_achat = df_brut1.rename(columns=dico_colonnes)
df_pouvoir_achat

     code_zone_insee  annee_recensement indicateur   valeur
0     2026-COM-75056               2023     MED_SL  33650.0
1     2026-COM-75056               2023    PR_MD60     16.8
2     2026-COM-77001               2023     MED_SL  34840.0
3     2026-COM-77002               2023     MED_SL  29130.0
4     2026-COM-77003               2023     MED_SL  30310.0
...              ...                ...        ...      ...
1790  2026-COM-95678               2023     MED_SL  34300.0
1791  2026-COM-95680               2023     MED_SL  17750.0
1792  2026-COM-95680               2023    PR_MD60     39.4
1793  2026-COM-95682               2023     MED_SL  28800.0
1794  2026-COM-95690               2023     MED_SL  35370.0

[1795 rows x 4 columns]

In [56]:
# df_pouvoir_achat['unite_measure'].unique()

In [49]:
df_pouvoir_achat['indicateur'].unique()

<StringArray>
['MED_SL', 'PR_MD60']
Length: 2, dtype: str

In [50]:
df_pouvoir_achat = (
    df_pouvoir_achat
    .pivot_table(
        index=["code_zone_insee", "annee_recensement"],
        columns="indicateur",
        values="valeur",
        aggfunc="first"
    )
    .reset_index()
)
df_pouvoir_achat

indicateur code_zone_insee  annee_recensement   MED_SL  PR_MD60
0           2026-COM-75056               2023  33650.0     16.8
1           2026-COM-77001               2023  34840.0      NaN
2           2026-COM-77002               2023  29130.0      NaN
3           2026-COM-77003               2023  30310.0      NaN
4           2026-COM-77004               2023  31970.0      NaN
...                    ...                ...      ...      ...
1247        2026-COM-95676               2023  30180.0      NaN
1248        2026-COM-95678               2023  34300.0      NaN
1249        2026-COM-95680               2023  17750.0     39.4
1250        2026-COM-95682               2023  28800.0      NaN
1251        2026-COM-95690               2023  35370.0      NaN

[1252 rows x 4 columns]

In [51]:
dictionnaire_filosofi = {
   
    # Pauvreté et niveau de vie
    "PR_MD60": "taux_pauvrete_60",
    "MED_SL": "niveau_vie_median"
}
df_pouvoir_achat.rename(columns=dictionnaire_filosofi, inplace=True)
df_pouvoir_achat

indicateur,code_zone_insee,annee_recensement,niveau_vie_median,taux_pauvrete_60
0,2026-COM-75056,2023,33650.0,16.8
1,2026-COM-77001,2023,34840.0,NaN
2,2026-COM-77002,2023,29130.0,NaN
3,2026-COM-77003,2023,30310.0,NaN
4,2026-COM-77004,2023,31970.0,NaN
...,...,...,...,...
1247,2026-COM-95676,2023,30180.0,NaN
1248,2026-COM-95678,2023,34300.0,NaN
1249,2026-COM-95680,2023,17750.0,39.4
1250,2026-COM-95682,2023,28800.0,NaN
1251,2026-COM-95690,2023,35370.0,NaN

In [52]:
# Chargement de la table finale dans la base de données
df_pouvoir_achat.to_sql("fin_pouvoir_achat_population", con=engine, if_exists="replace", index=False)

252

##### Table stg_population_recensement

In [60]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_recensement;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 35448 lignes.

,GEO,SEX,FREQ,TIME_PERIOD,RP_MEASURE,AGE,OBS_VALUE_NIVEAU
0,2026-COM-75056,F,A,2023,POP,Y_LT15,132320.39648
1,2026-COM-75056,M,A,2023,POP,Y_LT15,135938.81676
2,2026-COM-77001,F,A,2023,POP,Y_LT15,92.15548
3,2026-COM-77001,M,A,2023,POP,Y_LT15,89.25721
4,2026-COM-77002,F,A,2023,POP,Y_LT15,64.89686
...,...,...,...,...,...,...,...
35443,2026-COM-95680,M,A,2017,POP,Y_GE65,1368.71539
35444,2026-COM-95682,F,A,2017,POP,Y_GE65,9.78836
35445,2026-COM-95682,M,A,2017,POP,Y_GE65,9.78836
35446,2026-COM-95690,F,A,2017,POP,Y_GE65,39.22843
35447,2026-COM-95690,M,A,2017,POP,Y_GE65,29.10089

In [61]:
print(df_brut["SEX"].unique())
print(df_brut["AGE"].unique())
print(df_brut["RP_MEASURE"].unique())
print(df_brut["FREQ"].unique())

<StringArray>
['F', 'M']
Length: 2, dtype: str
<StringArray>
['Y_LT15', 'Y15T24', 'Y20T64', 'Y25T39', 'Y40T54', 'Y55T64', 'Y_GE65']
Length: 7, dtype: str
<StringArray>
['POP']
Length: 1, dtype: str
<StringArray>
['A']
Length: 1, dtype: str

In [62]:
dico_sexe = {
    "F": "femmes",
    "M": "hommes"
}

df_brut["SEX"] = df_brut["SEX"].replace(dico_sexe)

In [63]:
dico_age = {
    "Y_LT15": "moins_de_15_ans",
    "Y15T24": "15_24_ans",
    "Y20T64": "20_64_ans",
    "Y25T39": "25_39_ans",
    "Y40T54": "40_54_ans",
    "Y55T64": "55_64_ans",
    "Y_GE65": "65_ans_et_plus"
}

df_brut["AGE"] = df_brut["AGE"].replace(dico_age)
df_brut

,GEO,SEX,FREQ,TIME_PERIOD,RP_MEASURE,AGE,OBS_VALUE_NIVEAU
0,2026-COM-75056,femmes,A,2023,POP,moins_de_15_ans,132320.39648
1,2026-COM-75056,hommes,A,2023,POP,moins_de_15_ans,135938.81676
2,2026-COM-77001,femmes,A,2023,POP,moins_de_15_ans,92.15548
3,2026-COM-77001,hommes,A,2023,POP,moins_de_15_ans,89.25721
4,2026-COM-77002,femmes,A,2023,POP,moins_de_15_ans,64.89686
...,...,...,...,...,...,...,...
35443,2026-COM-95680,hommes,A,2017,POP,65_ans_et_plus,1368.71539
35444,2026-COM-95682,femmes,A,2017,POP,65_ans_et_plus,9.78836
35445,2026-COM-95682,hommes,A,2017,POP,65_ans_et_plus,9.78836
35446,2026-COM-95690,femmes,A,2017,POP,65_ans_et_plus,39.22843
35447,2026-COM-95690,hommes,A,2017,POP,65_ans_et_plus,29.10089

In [64]:
df_brut1 = df_brut.rename(columns={
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",
    "SEX": "sexe",
    "AGE": "tranche_age",
    "OBS_VALUE_NIVEAU": "population"
})
df_brut1

,code_zone_insee,sexe,FREQ,annee_recensement,RP_MEASURE,tranche_age,population
0,2026-COM-75056,femmes,A,2023,POP,moins_de_15_ans,132320.39648
1,2026-COM-75056,hommes,A,2023,POP,moins_de_15_ans,135938.81676
2,2026-COM-77001,femmes,A,2023,POP,moins_de_15_ans,92.15548
3,2026-COM-77001,hommes,A,2023,POP,moins_de_15_ans,89.25721
4,2026-COM-77002,femmes,A,2023,POP,moins_de_15_ans,64.89686
...,...,...,...,...,...,...,...
35443,2026-COM-95680,hommes,A,2017,POP,65_ans_et_plus,1368.71539
35444,2026-COM-95682,femmes,A,2017,POP,65_ans_et_plus,9.78836
35445,2026-COM-95682,hommes,A,2017,POP,65_ans_et_plus,9.78836
35446,2026-COM-95690,femmes,A,2017,POP,65_ans_et_plus,39.22843
35447,2026-COM-95690,hommes,A,2017,POP,65_ans_et_plus,29.10089

In [65]:
df_brut1 = df_brut1.drop(columns=["RP_MEASURE", "FREQ"])
df_brut1

,code_zone_insee,sexe,annee_recensement,tranche_age,population
0,2026-COM-75056,femmes,2023,moins_de_15_ans,132320.39648
1,2026-COM-75056,hommes,2023,moins_de_15_ans,135938.81676
2,2026-COM-77001,femmes,2023,moins_de_15_ans,92.15548
3,2026-COM-77001,hommes,2023,moins_de_15_ans,89.25721
4,2026-COM-77002,femmes,2023,moins_de_15_ans,64.89686
...,...,...,...,...,...
35443,2026-COM-95680,hommes,2017,65_ans_et_plus,1368.71539
35444,2026-COM-95682,femmes,2017,65_ans_et_plus,9.78836
35445,2026-COM-95682,hommes,2017,65_ans_et_plus,9.78836
35446,2026-COM-95690,femmes,2017,65_ans_et_plus,39.22843
35447,2026-COM-95690,hommes,2017,65_ans_et_plus,29.10089

In [66]:
df_population = df_brut1.copy()

# Création du nom de l'indicateur
df_population["indicateur"] = (
    "population_"
    + df_population["sexe"]
    + "_"
    + df_population["tranche_age"]
)

# Pivot
df_population = (
    df_population
    .pivot(
        index=["code_zone_insee", "annee_recensement"],
        columns="indicateur",
        values="population"
    )
    .reset_index()
)

# Supprimer le nom de l'axe des colonnes
df_population.columns.name = None
df_population

,code_zone_insee,annee_recensement,population_femmes_15_24_ans,population_femmes_20_64_ans,population_femmes_25_39_ans,population_femmes_40_54_ans,population_femmes_55_64_ans,population_femmes_65_ans_et_plus,population_femmes_moins_de_15_ans,population_hommes_15_24_ans,population_hommes_20_64_ans,population_hommes_25_39_ans,population_hommes_40_54_ans,population_hommes_55_64_ans,population_hommes_65_ans_et_plus,population_hommes_moins_de_15_ans
0,2026-COM-75056,2017,156628.07670,734578.03119,289922.25801,217959.61753,129078.58331,215781.20416,149252.95972,133226.81558,670144.02184,273590.47006,207517.92455,111164.92183,149643.98645,153759.18212
1,2026-COM-75056,2023,161961.91248,705247.08321,279018.79281,199372.77055,124520.14053,218245.61597,132320.39648,133867.97450,644314.31776,261920.93496,190681.33483,112165.74548,153763.56465,135938.81676
2,2026-COM-77001,2017,60.27395,344.40513,74.40235,173.42868,72.23879,92.19940,98.19962,82.05203,339.36545,58.83414,169.23923,68.15643,82.85583,93.11954
3,2026-COM-77001,2023,58.62215,361.47290,84.17933,158.49481,98.48529,125.40563,92.15548,56.53079,338.67106,72.12427,140.98488,107.34178,107.41838,89.25721
4,2026-COM-77002,2017,37.78850,235.77024,81.54360,75.66634,65.63266,86.97368,70.60483,34.80520,230.88741,71.59926,75.66634,69.69973,75.46514,79.55473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527,2026-COM-95680,2023,2200.41646,8612.24546,3191.51576,2835.64835,1537.04426,1617.32867,3783.44778,2157.05979,8325.92884,3046.40407,2758.21052,1478.77793,1423.18991,4023.95651
2528,2026-COM-95682,2017,7.83069,55.79365,24.47090,20.55556,5.87302,9.78836,17.61905,8.80952,56.77249,19.57672,24.47090,6.85185,9.78836,29.36508
2529,2026-COM-95682,2023,3.72727,58.70455,27.95455,16.77273,13.04545,9.31818,31.68182,12.11364,63.36364,23.29545,23.29545,13.04545,5.59091,25.15909
2530,2026-COM-95690,2017,14.73995,97.32795,26.68038,38.68656,26.01684,39.22843,21.64429,13.76902,111.36202,28.71856,36.73352,37.04034,29.10089,20.64122
2531,2026-COM-95690,2023,12.75267,99.09550,24.64882,29.60348,38.95417,39.27131,17.58908,7.82575,93.11491,22.68557,27.58805,37.95338,34.13233,32.99539

In [67]:
df_population.to_sql("fin_recensement_population", con=engine, if_exists="replace", index=False)

532

##### Table stg_population_reference

In [68]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_reference;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 3798 lignes.

                 GEO FREQ  TIME_PERIOD POPREF_MEASURE  OBS_VALUE_NIVEAU
0     2025-COM-77280    A         2023           PCAP               6.0
1     2025-COM-77169    A         2023           PCAP              51.0
2     2025-COM-77214    A         2023           PMUN             807.0
3     2025-COM-77242    A         2023           PTOT             554.0
4     2025-COM-77237    A         2023           PTOT             660.0
...              ...  ...          ...            ...               ...
3793  2025-COM-95387    A         2023           PCAP               0.0
3794  2025-COM-95288    A         2023           PMUN            8453.0
3795  2025-COM-95120    A         2023           PTOT            2279.0
3796  2025-COM-95253    A         2023           PCAP               8.0
3797  2025-COM-95058    A         2023           PCAP              24.0

[3798 rows x 5 columns]

In [69]:
print(df_brut["POPREF_MEASURE"].unique())

<StringArray>
['PCAP', 'PMUN', 'PTOT']
Length: 3, dtype: str

In [70]:
df = df_brut.rename(columns={
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",
    "POPREF_MEASURE": "type_population",
    "OBS_VALUE_NIVEAU": "valeur_population"
})

In [71]:
dico_popref = {
    "_T": "ensemble",

    "PCAP": "population_au_sens_large_non_residente",
    "PMUN": "population_municipale",
    "PTOT": "population_totale"
}
df["type_population"] = df["type_population"].replace(dico_popref)
df

,code_zone_insee,FREQ,annee_recensement,type_population,valeur_population
0,2025-COM-77280,A,2023,population_au_sens_large_non_residente,6.0
1,2025-COM-77169,A,2023,population_au_sens_large_non_residente,51.0
2,2025-COM-77214,A,2023,population_municipale,807.0
3,2025-COM-77242,A,2023,population_totale,554.0
4,2025-COM-77237,A,2023,population_totale,660.0
...,...,...,...,...,...
3793,2025-COM-95387,A,2023,population_au_sens_large_non_residente,0.0
3794,2025-COM-95288,A,2023,population_municipale,8453.0
3795,2025-COM-95120,A,2023,population_totale,2279.0
3796,2025-COM-95253,A,2023,population_au_sens_large_non_residente,8.0
3797,2025-COM-95058,A,2023,population_au_sens_large_non_residente,24.0

In [72]:
df_pop_ref = (
    df.pivot_table(
        index=["code_zone_insee", "annee_recensement"],
        columns="type_population",
        values="valeur_population",
        aggfunc="first"
    )
    .reset_index()
)
df_pop_ref

type_population,code_zone_insee,annee_recensement,population_au_sens_large_non_residente,population_municipale,population_totale
0,2025-COM-75056,2023,15634.0,2103778.0,2119412.0
1,2025-COM-77001,2023,32.0,1191.0,1223.0
2,2025-COM-77002,2023,5.0,830.0,835.0
3,2025-COM-77003,2023,8.0,349.0,357.0
4,2025-COM-77004,2023,2.0,336.0,338.0
...,...,...,...,...,...
1261,2025-COM-95676,2023,7.0,498.0,505.0
1262,2025-COM-95678,2023,16.0,858.0,874.0
1263,2025-COM-95680,2023,142.0,30053.0,30195.0
1264,2025-COM-95682,2023,2.0,205.0,207.0
1265,2025-COM-95690,2023,4.0,326.0,330.0

In [73]:
df_pop_ref.to_sql("fin_reference_population", con=engine, if_exists="replace", index=False)

266

##### Table stg_population_remuneration

In [74]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_remuneration;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 7596 lignes.

,GEO,ECONOMIC_SPHERE,FLORES_MEASURE,FREQ,LEGAL_FORM_WITH_PUBLIC,TIME_PERIOD,OBS_STATUS,OBS_VALUE_NIVEAU
0,2026-COM-75056,PRESENTIAL,EMPL3112,A,1T4,2024,A,358360.0
1,2026-COM-75056,PRESENTIAL,EMPL3112,A,5T9X7,2024,A,927201.0
2,2026-COM-75056,PRESENTIAL,EMPL3112,A,1T9X7,2024,A,1285561.0
3,2026-COM-75056,PRESENTIAL,UNIT_LOC,A,1T4,2024,A,3169.0
4,2026-COM-75056,PRESENTIAL,UNIT_LOC,A,5T9X7,2024,A,111158.0
...,...,...,...,...,...,...,...,...
7591,2026-COM-95690,PRESENTIAL,EMPL3112,A,5T9X7,2024,A,17.0
7592,2026-COM-95690,PRESENTIAL,EMPL3112,A,1T9X7,2024,A,24.0
7593,2026-COM-95690,PRESENTIAL,UNIT_LOC,A,1T4,2024,A,3.0
7594,2026-COM-95690,PRESENTIAL,UNIT_LOC,A,5T9X7,2024,A,5.0
7595,2026-COM-95690,PRESENTIAL,UNIT_LOC,A,1T9X7,2024,A,8.0

In [75]:
print(df_brut["ECONOMIC_SPHERE"].unique())
print(df_brut["FLORES_MEASURE"].unique())
print(df_brut["LEGAL_FORM_WITH_PUBLIC"].unique())

<StringArray>
['PRESENTIAL']
Length: 1, dtype: str
<StringArray>
['EMPL3112', 'UNIT_LOC']
Length: 2, dtype: str
<StringArray>
['1T4', '5T9X7', '1T9X7']
Length: 3, dtype: str

In [79]:
df_flores = df_brut.copy()

# Création de l'indicateur
df_flores["indicateur"] = (
    df_flores["FLORES_MEASURE"]
    + "_"
    + df_flores["LEGAL_FORM_WITH_PUBLIC"]
)

# Pivot
df_flores = (
    df_flores
    .pivot(
        index=["GEO", "TIME_PERIOD"],
        columns="indicateur",
        values="OBS_VALUE_NIVEAU"
    )
    .reset_index()
)

df_flores.columns.name = None
df_flores

,GEO,TIME_PERIOD,EMPL3112_1T4,EMPL3112_1T9X7,EMPL3112_5T9X7,UNIT_LOC_1T4,UNIT_LOC_1T9X7,UNIT_LOC_5T9X7
0,2026-COM-75056,2024,358360.0,1285561.0,927201.0,3169.0,114327.0,111158.0
1,2026-COM-77001,2024,35.0,129.0,94.0,3.0,14.0,11.0
2,2026-COM-77002,2024,21.0,182.0,161.0,3.0,25.0,22.0
3,2026-COM-77003,2024,8.0,34.0,26.0,3.0,6.0,3.0
4,2026-COM-77004,2024,4.0,13.0,9.0,2.0,7.0,5.0
...,...,...,...,...,...,...,...,...
1261,2026-COM-95676,2024,13.0,47.0,34.0,3.0,10.0,7.0
1262,2026-COM-95678,2024,16.0,62.0,46.0,2.0,20.0,18.0
1263,2026-COM-95680,2024,1515.0,4212.0,2697.0,33.0,494.0,461.0
1264,2026-COM-95682,2024,3.0,18.0,15.0,1.0,5.0,4.0
1265,2026-COM-95690,2024,7.0,24.0,17.0,3.0,8.0,5.0

In [80]:
df_flores = df_flores.rename(columns={
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement",
    "EMPL3112_1T4": "emplois_entreprises_individuelles",
    "EMPL3112_5T9X7": "emplois_entreprises_privees_toutes_formes",
    "EMPL3112_1T9X7": "emplois_secteur_public_et_prive_melange",

    "UNIT_LOC_1T4": "unites_locales_entreprises_individuelles",
    "UNIT_LOC_5T9X7": "unites_locales_entreprises_privees_toutes_formes",
    "UNIT_LOC_1T9X7": "unites_locales_secteur_public_et_prive_melange"
})
df_flores

,code_zone_insee,annee_recensement,emplois_entreprises_individuelles,emplois_secteur_public_et_prive_melange,emplois_entreprises_privees_toutes_formes,unites_locales_entreprises_individuelles,unites_locales_secteur_public_et_prive_melange,unites_locales_entreprises_privees_toutes_formes
0,2026-COM-75056,2024,358360.0,1285561.0,927201.0,3169.0,114327.0,111158.0
1,2026-COM-77001,2024,35.0,129.0,94.0,3.0,14.0,11.0
2,2026-COM-77002,2024,21.0,182.0,161.0,3.0,25.0,22.0
3,2026-COM-77003,2024,8.0,34.0,26.0,3.0,6.0,3.0
4,2026-COM-77004,2024,4.0,13.0,9.0,2.0,7.0,5.0
...,...,...,...,...,...,...,...,...
1261,2026-COM-95676,2024,13.0,47.0,34.0,3.0,10.0,7.0
1262,2026-COM-95678,2024,16.0,62.0,46.0,2.0,20.0,18.0
1263,2026-COM-95680,2024,1515.0,4212.0,2697.0,33.0,494.0,461.0
1264,2026-COM-95682,2024,3.0,18.0,15.0,1.0,5.0,4.0
1265,2026-COM-95690,2024,7.0,24.0,17.0,3.0,8.0,5.0

In [81]:
df_flores.to_sql("fin_emploi_forme_juridique", con=engine, if_exists="replace", index=False)

266

##### Table stg_population_transport

In [82]:
# 1. Extraction : On récupère la table brute de transition depuis PostGIS
df_brut = pd.read_sql("SELECT * FROM stg_population_transport;", con=engine)

print(f"[Info] Données brutes extraites de PostgreSQL : {len(df_brut)} lignes.")
df_brut

[Info] Données brutes extraites de PostgreSQL : 15192 lignes.

                  GEO  TIME_PERIOD WORK_AREA  OBS_VALUE_NIVEAU
0      2026-COM-75056         2023        10      715780.62511
1      2026-COM-77001         2023        10          88.69753
2      2026-COM-77002         2023        10          64.81709
3      2026-COM-77003         2023        10          19.04237
4      2026-COM-77004         2023        10          22.82017
...               ...          ...       ...               ...
15187  2026-COM-95676         2017     24T30           0.00000
15188  2026-COM-95678         2017     24T30           0.00000
15189  2026-COM-95680         2017     24T30          10.04761
15190  2026-COM-95682         2017     24T30           0.00000
15191  2026-COM-95690         2017     24T30           0.99243

[15192 rows x 4 columns]

In [86]:
print(df_brut["WORK_AREA"].unique())

<StringArray>
['10', '20_30', '21', '22', '23', '24T30']
Length: 6, dtype: str

In [87]:
dico_work_area = {
    "10": "travaille_dans_la_commune",
    "20_30": "travaille_hors_commune",
    "21": "travaille_dans_le_departement",
    "22": "travaille_dans_un_autre_departement_de_la_region",
    "23": "travaille_hors_region",
    "24T30": "travaille_hors_france_ou_non_precise"
}

In [88]:
df_brut["WORK_AREA"] = df_brut["WORK_AREA"].replace(dico_work_area)

df_brut

,GEO,TIME_PERIOD,WORK_AREA,OBS_VALUE_NIVEAU
0,2026-COM-75056,2023,travaille_dans_la_commune,715780.62511
1,2026-COM-77001,2023,travaille_dans_la_commune,88.69753
2,2026-COM-77002,2023,travaille_dans_la_commune,64.81709
3,2026-COM-77003,2023,travaille_dans_la_commune,19.04237
4,2026-COM-77004,2023,travaille_dans_la_commune,22.82017
...,...,...,...,...
15187,2026-COM-95676,2017,travaille_hors_france_ou_non_precise,0.00000
15188,2026-COM-95678,2017,travaille_hors_france_ou_non_precise,0.00000
15189,2026-COM-95680,2017,travaille_hors_france_ou_non_precise,10.04761
15190,2026-COM-95682,2017,travaille_hors_france_ou_non_precise,0.00000
15191,2026-COM-95690,2017,travaille_hors_france_ou_non_precise,0.99243

In [89]:
df_mobilite = (
    df_brut
    .pivot_table(
        index=["GEO", "TIME_PERIOD"],
        columns="WORK_AREA",
        values="OBS_VALUE_NIVEAU",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)
df_mobilite

WORK_AREA,GEO,TIME_PERIOD,travaille_dans_la_commune,travaille_dans_le_departement,travaille_dans_un_autre_departement_de_la_region,travaille_hors_commune,travaille_hors_france_ou_non_precise,travaille_hors_region
0,2026-COM-75056,2017,737170.63648,0.00000,322635.19055,342413.27286,5615.23373,14162.84858
1,2026-COM-75056,2023,715780.62511,0.00000,332899.34276,355116.01547,5035.32121,17181.35150
2,2026-COM-77001,2017,120.10614,212.32440,211.78010,445.53123,1.96017,19.46655
3,2026-COM-77001,2023,88.69753,235.62367,229.65689,495.33179,0.00000,30.05123
4,2026-COM-77002,2017,70.60483,205.84788,79.55473,292.36365,2.98330,3.97774
...,...,...,...,...,...,...,...,...
2527,2026-COM-95680,2023,1866.01330,3423.11005,5144.80650,8732.51925,3.49592,161.10679
2528,2026-COM-95682,2017,14.68254,45.02646,37.19577,82.22222,0.00000,0.00000
2529,2026-COM-95682,2023,10.25000,54.04545,31.68182,90.38636,0.00000,4.65909
2530,2026-COM-95690,2017,21.90888,74.45890,69.56004,155.96071,0.99243,10.94935
2531,2026-COM-95690,2023,23.84449,72.36467,64.17306,139.47592,0.00000,2.93819

In [90]:
df_mobilite.rename(columns={
    "GEO": "code_zone_insee",
    "TIME_PERIOD": "annee_recensement"
}, inplace=True)

df_mobilite.columns.name = None
df_mobilite

,code_zone_insee,annee_recensement,travaille_dans_la_commune,travaille_dans_le_departement,travaille_dans_un_autre_departement_de_la_region,travaille_hors_commune,travaille_hors_france_ou_non_precise,travaille_hors_region
0,2026-COM-75056,2017,737170.63648,0.00000,322635.19055,342413.27286,5615.23373,14162.84858
1,2026-COM-75056,2023,715780.62511,0.00000,332899.34276,355116.01547,5035.32121,17181.35150
2,2026-COM-77001,2017,120.10614,212.32440,211.78010,445.53123,1.96017,19.46655
3,2026-COM-77001,2023,88.69753,235.62367,229.65689,495.33179,0.00000,30.05123
4,2026-COM-77002,2017,70.60483,205.84788,79.55473,292.36365,2.98330,3.97774
...,...,...,...,...,...,...,...,...
2527,2026-COM-95680,2023,1866.01330,3423.11005,5144.80650,8732.51925,3.49592,161.10679
2528,2026-COM-95682,2017,14.68254,45.02646,37.19577,82.22222,0.00000,0.00000
2529,2026-COM-95682,2023,10.25000,54.04545,31.68182,90.38636,0.00000,4.65909
2530,2026-COM-95690,2017,21.90888,74.45890,69.56004,155.96071,0.99243,10.94935
2531,2026-COM-95690,2023,23.84449,72.36467,64.17306,139.47592,0.00000,2.93819

In [91]:
df_mobilite.to_sql("fin_mobilite_domicile_travail", con=engine, if_exists="replace", index=False)

532

Garantir l'Intégrité et les Performances (Index Spatiaux)
Pour valider l'aspect "garantit la disponibilité et l'intégrité" du référentiel, on doit créer des index spatiaux. Sans index GIST, une requête de zone de chalandise sur toute l'Île-de-France prendrait plusieurs minutes. Avec un index, elle prend quelques millisecondes.

In [122]:
from sqlalchemy import text

with engine.connect() as conn:
    # 1. Ajout de la colonne géométrique 'coordonnee_geographique' si elle n'existe pas
    conn.execute(text("ALTER TABLE stg_commerces_idf ADD COLUMN IF NOT EXISTS coordonnee_geographique geometry(Point, 4326);"))
    
    # 2. Remplissage de la colonne 'coordonnee_geographique' à partir de la longitude et la latitude
    conn.execute(text("""
        UPDATE stg_commerces_idf 
        SET coordonnee_geographique = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
        WHERE longitude IS NOT NULL AND latitude IS NOT NULL;
    """))
    
    # 3. Création de l'index spatial GIST
    conn.execute(text("CREATE INDEX IF NOT EXISTS idx_commerces_spatial ON stg_commerces_idf USING GIST (coordonnee_geographique);"))
    
    conn.commit()

print("Indexation spatiale GIST des commerces finalisée avec succès.")

Indexation spatiale GIST des commerces finalisée avec succès.

In [123]:
# Sauvegarde finale de la table des commerces avec géométrie dans PostGIS
query_com=f''' SELECT nom,secteur_metier,coordonnee_geographique FROM stg_commerces_idf;'''
df_commerces = pd.read_sql(query_com, con=engine)
df_commerces.to_sql("fin_localisation_commerces_idf", con=engine, if_exists="replace", index=False)

324

In [124]:
from sqlalchemy import text

with engine.connect() as conn:
    # 1. Ajout de la colonne géométrique 'geom' si elle n'existe pas
    conn.execute(text("ALTER TABLE stg_velos_comptage ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);"))
    
    # 2. Découpage du texte "Latitude, Longitude" et conversion en Point(Longitude, Latitude)
    # split_part(..., ',', 1) récupère la Latitude
    # split_part(..., ',', 2) récupère la Longitude
    conn.execute(text("""
        UPDATE stg_velos_comptage 
        SET geom = ST_SetSRID(
            ST_MakePoint(
                CAST(split_part("Coordonnées géographiques", ',', 2) AS double precision), -- X : Longitude
                CAST(split_part("Coordonnées géographiques", ',', 1) AS double precision)  -- Y : Latitude
            ), 
            4326
        )
        WHERE "Coordonnées géographiques" IS NOT NULL 
          AND "Coordonnées géographiques" LIKE '%,%';
    """))
    
    # 3. Création de l'index spatial GIST
    conn.execute(text("CREATE INDEX IF NOT EXISTS idx_velos_spatial ON stg_velos_comptage USING GIST (geom);"))
    
    conn.commit()

print("Indexation spatiale GIST des points de comptage vélos finalisée avec succès !")

Indexation spatiale GIST des points de comptage vélos finalisée avec succès !

In [125]:
# Sauvegarde finale de la table des commerces avec géométrie dans PostGIS
query_velo=f''' SELECT "Nom du site de comptage" as nom_station,"Date d'installation du site de comptage" as date_installation, geom as coordonnee_geographique FROM stg_velos_comptage;'''
df_velo = pd.read_sql(query_velo, con=engine)
df_velo.to_sql("fin_localisation_station_velo_idf", con=engine, if_exists="replace", index=False)

113

In [119]:
df_velo

,nom_station,date_installation,coordonnee_geographique
0,106 avenue Denfert Rochereau,2012-02-21,0101000020E610000060764F1E16AA024074EFE192E36A...
1,135 avenue Daumesnil,2013-01-18,0101000020E61000000F0C207C28110340A0A696ADF56B...
2,28 boulevard Diderot,2013-01-17,0101000020E61000001AA37554350103400E15E3FC4D6C...
3,28 boulevard Diderot,2013-01-17,0101000020E61000001AA37554350103400E15E3FC4D6C...
4,Voie Georges Pompidou,2017-12-14,0101000020E6100000850838842A3502402A745E63976C...
...,...,...,...
108,8 boulevard d'Indochine,2023-03-13,0101000020E6100000CD920035B52C03409AB1683A3B71...
109,97 avenue Denfert Rochereau,2012-02-21,0101000020E610000060EAE74D45AA0240096D3997E26A...
110,29 boulevard des Batignolles,2023-10-30,0101000020E6100000010000604197024036C5D5D2FD70...
111,8 boulevard d'Indochine,2023-03-13,0101000020E6100000CD920035B52C03409AB1683A3B71...
112,Totem Cours la Reine,2020-02-10,0101000020E6100000156F641EF9830240D8BB3FDEAB6E...

In [116]:
query_comm=f''' SELECT * FROM stg_commerces_idf;'''
df_comm = pd.read_sql(query_comm, con=engine)

In [117]:
df_comm

,nom,secteur_metier,tag_technique,latitude,longitude,coordonnee_geographique
0,Relais Total De Torfou,Autre service commercial,convenience;gas,48.562908,2.228316,0101000020E6100000BE33356497D30140CF9211610D48...
1,BP Avenue Paul Vaillant-Couturier,Autre service commercial,convenience;gas,48.927804,2.473818,0101000020E61000005727C2E160CA0340DE8A694BC276...
2,Carrefour city,Autre service commercial,convenience;gas,48.885314,2.504690,0101000020E61000004006E1C09A0904409BD7C7F95171...
3,Esso,Autre service commercial,convenience;gas,48.823134,2.493943,0101000020E6100000E2C1604898F30340E31C75745C69...
4,Esso,Alimentation,convenience,48.630123,2.486355,0101000020E61000002EDDC94C0EE40340B63984E0A750...
...,...,...,...,...,...,...
33319,Clean City,Services,laundry,48.805010,2.326200,0101000020E61000008D9D4BCC0E9C02408F392A920A67...
33320,Coco Nails,Beauté / Parfumerie,beauty,48.804947,2.326367,0101000020E6100000F5F23B4D669C0240B401D8800867...
33321,Boucherie LMD,Alimentation,butcher,48.805059,2.326678,0101000020E6100000C6803683099D0240F46E2C280C67...
33322,Carrefour,Alimentation,supermarket,48.804616,2.327062,0101000020E61000009A023EE4D29D02400D2ABBAAFD66...
33323,U Express,Alimentation,supermarket,48.529386,2.013612,0101000020E6100000C9CB9A58E01B004055BBCBEAC243...

##### Jointure des noms de commune et codes postaux

In [ ]:
# ALTER TABLE fin_localisation_commerces_idf
# ADD COLUMN IF NOT EXISTS code_postal VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_localisation_commerces_idf AS c
# SET code_postal = com.code_postal,
# nom_commune = com.nom_commune
# FROM fin_communes_geom AS com
# WHERE c.coordonnee_geographique IS NOT NULL
#   AND ST_Covers(com.geom, c.coordonnee_geographique::geometry);


# ALTER TABLE fin_localisation_station_velo_idf
# ADD COLUMN IF NOT EXISTS code_postal VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_localisation_station_velo_idf AS c
# SET code_postal = com.code_postal,
# nom_commune = com.nom_commune
# FROM fin_communes_geom AS com
# WHERE c.coordonnee_geographique IS NOT NULL
#   AND ST_Covers(com.geom, c.coordonnee_geographique::geometry);

In [ ]:
from sqlalchemy import text


query = text("""
-- ============================================================
-- 1. LOCALISATION DES COMMERCES
-- ============================================================

ALTER TABLE fin_localisation_commerces_idf
    ADD COLUMN IF NOT EXISTS code_postal VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_localisation_commerces_idf AS c
SET
    code_postal = com.code_postal,
    nom_commune = com.nom_commune
FROM fin_communes_geom AS com
WHERE c.coordonnee_geographique IS NOT NULL
  AND ST_Covers(
        com.geom,
        c.coordonnee_geographique::geometry
      );


-- ============================================================
-- 2. LOCALISATION DES STATIONS VÉLO
-- ============================================================

ALTER TABLE fin_localisation_station_velo_idf
    ADD COLUMN IF NOT EXISTS code_postal VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_localisation_station_velo_idf AS c
SET
    code_postal = com.code_postal,
    nom_commune = com.nom_commune
FROM fin_communes_geom AS com
WHERE c.coordonnee_geographique IS NOT NULL
  AND ST_Covers(
        com.geom,
        c.coordonnee_geographique::geometry
      );
""")


with engine.begin() as conn:
    conn.execute(query)


print(
    "✓ Les tables de localisation des commerces "
    "et des stations vélo ont été mises à jour."
)

#### Division de la colonne GEO en millesime et code insee

In [ ]:
# ALTER TABLE fin_attractivite_socioeconomique  
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_attractivite_socioeconomique 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');

# ALTER TABLE fin_caracteristiques_logement   
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_caracteristiques_logement 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


# ALTER TABLE fin_emploi_forme_juridique   
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_emploi_forme_juridique 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


# ALTER TABLE fin_infrastructures_de_proximite   
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_infrastructures_de_proximite 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


# ALTER TABLE fin_mobilite_domicile_travail  
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_mobilite_domicile_travail 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


# ALTER TABLE fin_population_emploi
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_population_emploi 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');

# ALTER TABLE fin_pouvoir_achat_population 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_pouvoir_achat_population 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');

# ALTER TABLE fin_recensement_population 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_recensement_population 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


# ALTER TABLE fin_reference_population 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
# ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);


# UPDATE fin_reference_population 
# SET
#     code_commune = substring(code_zone_insee FROM '(\d{5})$'),
#     millesime_referentiel_geo = substring(code_zone_insee FROM '^(\d{4})')::INTEGER,
#     niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');

In [ ]:
query = text("""
ALTER TABLE fin_attractivite_socioeconomique
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_attractivite_socioeconomique
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_caracteristiques_logement
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_caracteristiques_logement
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_emploi_forme_juridique
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_emploi_forme_juridique
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_infrastructures_de_proximite
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_infrastructures_de_proximite
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_mobilite_domicile_travail
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_mobilite_domicile_travail
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_population_emploi
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_population_emploi
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_pouvoir_achat_population
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_pouvoir_achat_population
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_recensement_population
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_recensement_population
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');


ALTER TABLE fin_reference_population
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS millesime_referentiel_geo INTEGER,
    ADD COLUMN IF NOT EXISTS niveau_geo VARCHAR(10);

UPDATE fin_reference_population
SET
    code_commune = substring(code_zone_insee FROM '(\\d{5})$'),
    millesime_referentiel_geo = substring(code_zone_insee FROM '^(\\d{4})')::INTEGER,
    niveau_geo = substring(code_zone_insee FROM '-([A-Z]+)-');
""")


with engine.begin() as conn:
    conn.execute(query)

print("✓ Toutes les tables ont été mises à jour.")

#### Jointure avec la table commune annee pour avoir les noms des communes

In [ ]:

# -- 2. fin_caracteristiques_logement
# ALTER TABLE fin_caracteristiques_logement 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_caracteristiques_logement AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


# -- 4. fin_emploi_forme_juridique
# ALTER TABLE fin_emploi_forme_juridique 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_emploi_forme_juridique AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

# -- 5. fin_infrastructures_de_proximite
# ALTER TABLE fin_infrastructures_de_proximite 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_infrastructures_de_proximite AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

# -- 6. fin_mobilite_domicile_travail
# ALTER TABLE fin_mobilite_domicile_travail 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_mobilite_domicile_travail AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

# -- 7. fin_population_emploi
# ALTER TABLE fin_population_emploi 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_population_emploi AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

# -- 8. fin_pouvoir_achat_population
# ALTER TABLE fin_pouvoir_achat_population 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_pouvoir_achat_population AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

# -- 9. fin_recensement_population
# ALTER TABLE fin_recensement_population 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_recensement_population AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

# -- 10. fin_reference_population
# ALTER TABLE fin_reference_population 
# ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
# ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

# UPDATE fin_reference_population AS t
# SET 
#     code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
#     nom_commune = ca.nom_commune
# FROM commune_annee ca
# WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;

In [ ]:
from sqlalchemy import text

query = text("""
-- ============================================================
-- 2. fin_caracteristiques_logement
-- ============================================================

ALTER TABLE fin_caracteristiques_logement
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_caracteristiques_logement AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 4. fin_emploi_forme_juridique
-- ============================================================

ALTER TABLE fin_emploi_forme_juridique
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_emploi_forme_juridique AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 5. fin_infrastructures_de_proximite
-- ============================================================

ALTER TABLE fin_infrastructures_de_proximite
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_infrastructures_de_proximite AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 6. fin_mobilite_domicile_travail
-- ============================================================

ALTER TABLE fin_mobilite_domicile_travail
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_mobilite_domicile_travail AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 7. fin_population_emploi
-- ============================================================

ALTER TABLE fin_population_emploi
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_population_emploi AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 8. fin_pouvoir_achat_population
-- ============================================================

ALTER TABLE fin_pouvoir_achat_population
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_pouvoir_achat_population AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 9. fin_recensement_population
-- ============================================================

ALTER TABLE fin_recensement_population
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_recensement_population AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;


-- ============================================================
-- 10. fin_reference_population
-- ============================================================

ALTER TABLE fin_reference_population
    ADD COLUMN IF NOT EXISTS code_commune VARCHAR(5),
    ADD COLUMN IF NOT EXISTS nom_commune VARCHAR(150);

UPDATE fin_reference_population AS t
SET
    code_commune = SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$'),
    nom_commune = ca.nom_commune
FROM commune_annee ca
WHERE SUBSTRING(t.code_zone_insee FROM '[0-9]{5}$') = ca.code_commune;
""")

with engine.begin() as conn:
    conn.execute(query)

print("✓ Les tables socio-économiques ont été mises à jour avec le code et le nom de commune.")

##### Création des colonnes annee_recensement à commerces idf et velo idf

In [ ]:

# ALTER TABLE fin_localisation_commerces_idf
# ADD COLUMN annee_recensement INT;

# UPDATE fin_localisation_commerces_idf
# SET annee_recensement = 2025; 

# ALTER TABLE fin_localisation_station_velo_idf
# ADD COLUMN annee_recensement INT;

# UPDATE fin_localisation_station_velo_idf
# SET annee_recensement = 2025;

#### Vérif si les données contiennent l'année la plus récente

In [ ]:
from airflow.operators.python import ShortCircuitOperator
from sqlalchemy import create_engine, text


def verifier_nouvelle_annee():

    engine = create_engine(
        "postgresql+psycopg2://USER:PASSWORD@HOST:5432/DATABASE"
    )

    tables_fin = [
        "fin_caracteristiques_logement",
        "fin_emploi_forme_juridique",
        "fin_infrastructures_de_proximite",
        "fin_mobilite_domicile_travail",
        "fin_population_emploi",
        "fin_pouvoir_achat_population",
        "fin_recensement_population",
        "fin_reference_population"
    ]

    annee_actuelle = 2025

    annees_trouvees = []

    with engine.connect() as conn:

        for table in tables_fin:

            query = text(f"""
                SELECT MAX(annee_recensement) AS derniere_annee
                FROM {table}
                WHERE annee_recensement IS NOT NULL
            """)

            resultat = conn.execute(query).scalar()

            if resultat is not None:
                annees_trouvees.append(int(resultat))

    if not annees_trouvees:
        print("❌ Aucune année trouvée.")
        return False

    derniere_annee = max(annees_trouvees)

    print(f"Année actuellement traitée : {annee_actuelle}")
    print(f"Dernière année disponible : {derniere_annee}")

    if derniere_annee > annee_actuelle:

        print(
            f"✅ Nouvelle année détectée : {derniere_annee}. "
            "La modélisation va continuer."
        )

        return True

    print(
        "⏹️ Aucune nouvelle année disponible. "
        "La suite du DAG sera ignorée."
    )

    return False